### PR TITLE
Enable project specific  web hook

### PR DESCRIPTION
**Pull request by el95149**
Hi @sleroy , I'm creating the PR for my changes, since I didn't see them in your repo.

Let me know what you need help with.

Angelos Anagnostopoulos

### CODE REVIEW

**Comment by el95149** [comment]
I'll resolve the conflicts, if you confirm you'll merge it afterwards. Thanks.

**Comment by sleroy** [comment]
Hello,

If the conflicts are not too important, I will merge it myself this evening.

Best,

Silvan

**Comment by el95149** [comment]
Thanks, cheers.

**Comment by sleroy** [comment]
new version released and ready to test if you have some time.

https://github.com/sleroy/sonar-slack-notifier-plugin/releases/tag/2.5

**Comment by el95149** [comment]
Will do, only possible glitch I see is I'm running Sonar 6.7, let's hope I don't get any problems because of that.
Any specific features you want me to look at, aside from the project specific hooks?

**Pull request merged**
